version: '3'

# $ cd /mnt/c/Users/andre/Documents/Angular-Docker-Cero-Experto/doc/ejercicios/06-postgress-pgAdmin-bindVolume
# andre@MSI:/mnt/c/Users/andre/Documents/Angular-Docker-Cero-Experto/doc/ejercicios/06-postgress-pgAdmin-bindVolume$ docker compose up

# Crea una aplicacion de multiples contenedores, lo que no hace falta una red para comunicarse
services:
  db:
    container_name: postgres_databasesudo
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - "5433:5432"  # Puerto expuesto para conexiones desde host
    volumes:
      # Bind mount para persistencia (con wsl), vuelva en /home/{user}/, no se puede acceder desde windows
      - ~/postgres-data:/var/lib/postgresql/data  
      # Bind mount para persistencia (sin wsl)
#      - ./postgres-data:/var/lib/postgresql/data  
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    restart: unless-stopped
    ports:
      - "8080:80"  # Acceso web: http://localhost:8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456
